# Generated by Django 5.1.3 on 2024-12-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_programer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Sex', models.CharField(max_length=1)),
                ('Numtoken', models.PositiveBigIntegerField(max_length=7)),
                ('Formationstatus', models.BooleanField(default=True)),
                ('Admissiondate', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
